# Generated by Django 6.0.8 on 2026-09-28 21:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym', '0008_auto_20190618_1617'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GymCheckInItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('pre', 'Pre-workout'), ('post', 'Post-workout'), ('daily', 'Daily'), ('biweekly', 'Bi-weekly')], max_length=16)),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('value_type', models.CharField(choices=[('number', 'Number'), ('scale_1_5', '1-5 scale'), ('yes_no', 'Yes/No')], max_length=16)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkin_items', to='gym.gym')),
            ],
            options={
                'ordering': ['kind', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='GymEconomyOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=32)),
                ('key', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='economy_overrides', to='gym.gym')),
            ],
            options={
                'unique_together': {('gym', 'section', 'key')},
            },
        ),
        migrations.CreateModel(
            name='MemberItemOptOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opt_outs', to='companion_gym.gymcheckinitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companion_checkin_opt_outs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('item', 'user')},
            },
        ),
    ]
